package org.runelight.util;

import java.util.LinkedHashMap;
import java.util.Map;

public final class CountryUtil {

	public static final Map<String, String> COUNTRY_MAP = new LinkedHashMap<String, String>() {
		
		private static final long serialVersionUID = 8547499868147837588L;
	
		{
			put("0", "Afghanistan");
			put("1", "Albania");
			put("2", "Algeria");
			put("3", "American Samoa");
			put("4", "Andorra");
			put("5", "Angola");
			put("6", "Anguilla");
			put("7", "Antarctica");
			put("8", "Antigua and Barbuda");
			put("9", "Argentina");
			put("10", "Armenia");
			put("11", "Aruba");
			put("12", "Australia");
			put("13", "Austria");
			put("14", "Azerbaijan");
			put("15", "Bahamas");
			put("16", "Bahrain");
			put("17", "Bangladesh");
			put("18", "Barbados");
			put("19", "Belarus");
			put("20", "Belgium");
			put("21", "Belize");
			put("22", "Benin");
			put("23", "Bermuda");
			put("24", "Bhutan");
			put("25", "Bolivia");
			put("26", "Bosnia and Herzegovina");
			put("27", "Botswana");
			put("28", "Bouvet Island");
			put("29", "Brazil");
			put("30", "British Indian Ocean Territory");
			put("31", "Brunei Darussalam");
			put("32", "Bulgaria");
			put("33", "Burkina Faso");
			put("34", "Burundi");
			put("35", "Cambodia");
			put("36", "Cameroon");
			put("37", "Canada");
			put("38", "Cape Verde");
			put("39", "Cayman Islands");
			put("40", "Central African Republic");
			put("41", "Chad");
			put("42", "Chile");
			put("43", "China");
			put("44", "Christmas Island");
			put("45", "Cocos (Keeling) Islands");
			put("46", "Colombia");
			put("47", "Comoros");
			put("48", "Congo");
			put("49", "Congo, the Democratic Republic of the");
			put("50", "Cook Islands");
			put("51", "Costa Rica");
			put("52", "Cote D'Ivoire");
			put("53", "Croatia");
			put("54", "Cuba");
			put("55", "Cyprus");
			put("56", "Czech Republic");
			put("57", "Denmark");
			put("58", "Djibouti");
			put("59", "Dominica");
			put("60", "Dominican Republic");
			put("61", "Ecuador");
			put("62", "Egypt");
			put("63", "El Salvador");
			put("64", "Equatorial Guinea");
			put("65", "Eritrea");
			put("66", "Estonia");
			put("67", "Ethiopia");
			put("68", "Falkland Islands (Malvinas)");
			put("69", "Faroe Islands");
			put("70", "Fiji");
			put("71", "Finland");
			put("72", "France");
			put("73", "French Guiana");
			put("74", "French Polynesia");
			put("75", "French Southern Territories");
			put("76", "Gabon");
			put("77", "Gambia");
			put("78", "Georgia");
			put("79", "Germany");
			put("80", "Ghana");
			put("81", "Gibraltar");
			put("82", "Greece");
			put("83", "Greenland");
			put("84", "Grenada");
			put("85", "Guadeloupe");
			put("86", "Guam");
			put("87", "Guatemala");
			put("88", "Guinea");
			put("89", "Guinea-Bissau");
			put("90", "Guyana");
			put("91", "Haiti");
			put("92", "Heard Island and Mcdonald Islands");
			put("93", "Holy See (Vatican City State)");
			put("94", "Honduras");
			put("95", "Hong Kong");
			put("96", "Hungary");
			put("97", "Iceland");
			put("98", "India");
			put("99", "Indonesia");
			put("100", "Iran, Islamic Republic of");
			put("101", "Iraq");
			put("102", "Ireland");
			put("103", "Israel");
			put("104", "Italy");
			put("105", "Jamaica");
			put("106", "Japan");
			put("107", "Jordan");
			put("108", "Kazakhstan");
			put("109", "Kenya");
			put("110", "Kiribati");
			put("111", "Korea, Democratic People's Republic of");
			put("112", "Korea, Republic of");
			put("113", "Kuwait");
			put("114", "Kyrgyzstan");
			put("115", "Lao People's Democratic Republic");
			put("116", "Latvia");
			put("117", "Lebanon");
			put("118", "Lesotho");
			put("119", "Liberia");
			put("120", "Libyan Arab Jamahiriya");
			put("121", "Liechtenstein");
			put("122", "Lithuania");
			put("123", "Luxembourg");
			put("124", "Macao");
			put("125", "Macedonia, the Former Yugoslav Republic of");
			put("126", "Madagascar");
			put("127", "Malawi");
			put("128", "Malaysia");
			put("129", "Maldives");
			put("130", "Mali");
			put("131", "Malta");
			put("132", "Marshall Islands");
			put("133", "Martinique");
			put("134", "Mauritania");
			put("135", "Mauritius");
			put("136", "Mayotte");
			put("137", "Mexico");
			put("138", "Micronesia, Federated States of");
			put("139", "Moldova, Republic of");
			put("140", "Monaco");
			put("141", "Mongolia");
			put("142", "Montserrat");
			put("143", "Morocco");
			put("144", "Mozambique");
			put("145", "Myanmar");
			put("146", "Namibia");
			put("147", "Nauru");
			put("148", "Nepal");
			put("149", "Netherlands");
			put("150", "Netherlands Antilles");
			put("151", "New Caledonia");
			put("152", "New Zealand");
			put("153", "Nicaragua");
			put("154", "Niger");
			put("155", "Nigeria");
			put("156", "Niue");
			put("157", "Norfolk Island");
			put("158", "Northern Mariana Islands");
			put("159", "Norway");
			put("160", "Oman");
			put("161", "Pakistan");
			put("162", "Palau");
			put("163", "Palestinian Territory, Occupied");
			put("164", "Panama");
			put("165", "Papua New Guinea");
			put("166", "Paraguay");
			put("167", "Peru");
			put("168", "Philippines");
			put("169", "Pitcairn");
			put("170", "Poland");
			put("171", "Portugal");
			put("172", "Puerto Rico");
			put("173", "Qatar");
			put("174", "Reunion");
			put("175", "Romania");
			put("176", "Russian Federation");
			put("177", "Rwanda");
			put("178", "Saint Helena");
			put("179", "Saint Kitts and Nevis");
			put("180", "Saint Lucia");
			put("181", "Saint Pierre and Miquelon");
			put("182", "Saint Vincent and the Grenadines");
			put("183", "Samoa");
			put("184", "San Marino");
			put("185", "Sao Tome and Principe");
			put("186", "Saudi Arabia");
			put("187", "Senegal");
			put("188", "Serbia and Montenegro");
			put("189", "Seychelles");
			put("190", "Sierra Leone");
			put("191", "Singapore");
			put("192", "Slovakia");
			put("193", "Slovenia");
			put("194", "Solomon Islands");
			put("195", "Somalia");
			put("196", "South Africa");
			put("197", "South Georgia and the South Sandwich Islands");
			put("198", "Spain");
			put("199", "Sri Lanka");
			put("200", "Sudan");
			put("201", "Suriname");
			put("202", "Svalbard and Jan Mayen");
			put("203", "Swaziland");
			put("204", "Sweden");
			put("205", "Switzerland");
			put("206", "Syrian Arab Republic");
			put("207", "Taiwan, Province of China");
			put("208", "Tajikistan");
			put("209", "Tanzania, United Republic of");
			put("210", "Thailand");
			put("211", "Timor-Leste");
			put("212", "Togo");
			put("213", "Tokelau");
			put("214", "Tonga");
			put("215", "Trinidad and Tobago");
			put("216", "Tunisia");
			put("217", "Turkey");
			put("218", "Turkmenistan");
			put("219", "Turks and Caicos Islands");
			put("220", "Tuvalu");
			put("221", "Uganda");
			put("222", "Ukraine");
			put("223", "United Arab Emirates");
			put("224", "United Kingdom");
			put("225", "United States");
			put("226", "United States Minor Outlying Islands");
			put("227", "Uruguay");
			put("228", "Uzbekistan");
			put("229", "Vanuatu");
			put("230", "Venezuela");
			put("231", "Vietnam");
			put("232", "Virgin Islands, British");
			put("233", "Virgin Islands, U.S.");
			put("234", "Wallis and Futuna");
			put("235", "Western Sahara");
			put("236", "Yemen");
			put("237", "Zambia");
			put("238", "Zimbabwe");
		}
		
	};
	
	public static boolean validCountry(String code) {
		return COUNTRY_MAP.containsKey(code);
	}
	
}
